/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_homework0_MainActivity */

#ifndef _Included_edu_stanford_homework0_MainActivity
#define _Included_edu_stanford_homework0_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_homework0_MainActivity
 * Method:    ORBFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_homework0_MainActivity_ORBFilter
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
